// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF8EzOQjLq-WC9ol0P0vjiP9K_hcWW3dA',
    appId: '1:51675241730:web:6759cf8d1c2ac1bd0f361b',
    messagingSenderId: '51675241730',
    projectId: 'event-app-e983e',
    authDomain: 'event-app-e983e.firebaseapp.com',
    storageBucket: 'event-app-e983e.appspot.com',
    measurementId: 'G-4XH4RNSX43',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb5f_Gi8yt7mQvoECkK2xC1D3-epGQBvw',
    appId: '1:51675241730:android:7ea12bd8b3db9dd60f361b',
    messagingSenderId: '51675241730',
    projectId: 'event-app-e983e',
    storageBucket: 'event-app-e983e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC64FdzQ6Mfvfy2pfGHYlVGsG3BNnehxuI',
    appId: '1:51675241730:ios:64e79bf0aec54a040f361b',
    messagingSenderId: '51675241730',
    projectId: 'event-app-e983e',
    storageBucket: 'event-app-e983e.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC64FdzQ6Mfvfy2pfGHYlVGsG3BNnehxuI',
    appId: '1:51675241730:ios:64e79bf0aec54a040f361b',
    messagingSenderId: '51675241730',
    projectId: 'event-app-e983e',
    storageBucket: 'event-app-e983e.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCF8EzOQjLq-WC9ol0P0vjiP9K_hcWW3dA',
    appId: '1:51675241730:web:86189017bb8cb42f0f361b',
    messagingSenderId: '51675241730',
    projectId: 'event-app-e983e',
    authDomain: 'event-app-e983e.firebaseapp.com',
    storageBucket: 'event-app-e983e.appspot.com',
    measurementId: 'G-2RW3E72WR8',
  );
}
